# OpenCLIP base model name
model_name: "ViT-B-16"
# Use these pretrained weights, provided by OpenCLIP
pretrained: "datacomp_xl_s13b_b90k"
compile: False
seed: 1337

device: "cuda"
# Output directory for finetuned lora weights and config. Will contain checkpoint folders with
# lora weights and config. Will be rewritten if using API
output_dir: "/Users/tman/work/bridge_output"

wandb: False
wandb_project: test-clipora

# Custom CSV dataset. If using API these paths will be rewritten to match the
# the extracted ZIP file paths
train_dataset: "/Users/tman/data/bridge_dataset_small/train.csv"
eval_dataset: "/Users/tman/data/bridge_dataset_small/eval.csv"
datatype: "csv"
csv_separator: ","
image_col: "image_path"
text_col: "language_instruction"
shuffle: True

lora_rank: 16
lora_alpha: 32
lora_dropout: 0.0

batch_size: 32
gradient_accumulation_steps: 1
gradient_checkpointing: False

use_8bit_adam: False

learning_rate: 1e-4
epochs: 3
warmup: 0.01
save_interval: 200
eval_interval: 30
eval_steps: 10
